#
# Module manifest for module 'PscxHelp'
#
# Generated by: Dan
#
# Generated on: 09.20.2021
#

@{
    RootModule = 'PscxHelp.psm1'
    ModuleVersion ="3.6.4"
    GUID = 'e50d3425-cdb8-4ab7-8241-c6253c7dd625'
    Author = 'PowerShell Core Community Extensions Team'
    CompanyName = 'PowerShell Core Community Extensions'
    Copyright = 'Copyright (c) 2005-2023 PowerShell Core Community Extensions Team. All rights reserved.'
    Description = 'PSCX Help module and utilities'
    PowerShellVersion = '7.2'
    DotNetFrameworkVersion = '6.0'
    ClrVersion = '6.0'
    RequiredAssemblies = @('Pscx.Help.dll')
    NestedModules = @('Pscx.Help.dll')

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = '*'

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('PSCX','Utilities','Help','Internal')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/danluca/Pscx/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/danluca/Pscx'

            # A URL to an icon representing this module.
            IconUri = 'https://github.com/danluca/Pscx/blob/master/PscxIcon.png?raw=true'

            # ReleaseNotes of this module
            ReleaseNotes = "See CHANGELOG.md file in PSCX module's root folder"

        } # End of PSData hashtable

    } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

